settings:
  jira_project_key: "DOCPR"
  epic_key: "DOCPR-2128"
  components:
    - Style Guide
  labels:
    - backlog
  status_mapping:
    opened: Untriaged
    closed: done
    # (Optional) Use different status for GitHub issues closed as not planned (instead of closed as
    # completed)
    # https://github.blog/changelog/2022-03-10-the-new-github-issues-march-10th-update/#%F0%9F%95%B5%F0%9F%8F%BD%E2%99%80%EF%B8%8F-issue-closed-reasons
    # If not specified, `closed` status will be used.
    not_planned: rejected
  # Adds a comment with the JIRA ID
  add_gh_comment: true
  # Reflect changes on JIRA
  sync_description: true
  # Comments are synced from Github to JIRA
  # Nothing goes from JIRA to Github
  sync_comments: true
  label_mapping:
    "Type: bug": Bug
    "Type: documentation": Task
    "Type: enhancement": Task
    "Type: improvement": Task
    "Type: question": Spike
