settings:
  jira_project_key: "DOCPR"
  epic_key: "DOCPR-2128"
  components:
    - Style Guide
  labels:
    - "Type: documentation"
    - "Type: enhancement"
    - "Type: improvement"
    - "Type: feature"
    - "Type | test"
  status_mapping:
    opened: Untriaged
    closed: done
    not_planned: rejected
  # Adds a comment with the JIRA ID
  add_gh_comment: true
  # Reflect changes on JIRA
  sync_description: true
  # Comments are synced from Github to JIRA
  # Nothing goes from JIRA to Github
  sync_comments: true
  label_mapping:
    "Type: bug": Bug
    "Type: documentation": Task
    "Type: enhancement": Task
    "Type: improvement": Task
    "Type: feature": Task
    "Type: question": Spike
    "Type | test": Task
